config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    resources :discussions, only: [:index]
    resources :replies, only: [:index]
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :custom_user_posts
  get 'users/:id/user_replies' => 'users#user_replies', :as => :custom_user_replies

  resources :topics
  resources :discussions do
  	resources :replies
  end
  resources :discussions do
    member do
      get :users
    end
  end

  root 'discussions#index'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/discussion.rb
# frozen_string_literal: true
class Discussion < ApplicationRecord

	# Creating relationships for the model
	# Topic and User references those tables
	belongs_to :topic
	belongs_to :user
	has_many :replies, dependent: :destroy

	# Don't allow the title or content to be submitted empty
	validates :title, :content, presence: true

	def increment(by =1 )
		self.view_count ||= 0
		self.view_count += by
		save
	end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_action :set_discussion, only: [:show, :edit, :update, :destroy] 
  # Call the method to get all topics and order them via created date
  # on pages index, show, new and edit
  before_action :find_topics, only: [:index, :show, :new, :edit]
  # Only allow users that are NOT signed in to view index and show
  # before_action :authenticate_user!, except: [:index, :show]

  # GET /discussions
  # GET /discussions.json
  def index
    # returns a list of discussions where the creation date is within the last 30 days
    # @discussions = Discussion.where('created_at > ?', 30.days.ago)
    if params[:toggle]
    @discussions = Discussion.order(params[:sort]).where(topic_id: params[:toggle]).order('created_at desc')
  else
    @discussions = Discussion.order(params[:sort]).
        where('created_at > ?', 30.days.ago)
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussions = Discussion.all.order('created_at desc')
    @discussion.increment
  end

  # GET /discussions/new
  def new
    if current_user
      @discussion = current_user.discussions.new
    else
      flash[:notice] = 'Please login before creating a discussion'
      redirect_to login_path
    end
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  def find_topics
    @topics = Topic.all.order('created_at desc')
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def discussion_params
    params.require(:discussion).permit(:title, :content, :topic_id)
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper

	# Checks if the user is the author of a discussion
	def discussion_author(discussion)
		logged_in? && current_user.id == discussion.user_id
	end

	# Checks if the user is the author of a reply
	def reply_author(reply)
		logged_in? && current_user.id == reply.user_id
	end

end

app/views/discussions/_form.html.erb
<%# Bulma used to create below %>

<%= simple_form_for(@discussion) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <div class="control">
      <%= f.input :title, required: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, required: true, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <label class="label">Topic</label>
    <div class="control has-icons-left">
      <span class="select">
        <%#= f.input_field :topic_id,  collection:@topics.map.collect{|c| [c.topic, c.id]}, :prompt => "Select Topic " %>
        <% options = [["Please select Topic", Topic.all.find_by(topic: "News").id]] + @topics.where.not(topic: "News").collect{ |i| [i.topic, i.id]} %>
        <%= f.select :topic_id, options_for_select(options) %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-tag"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, class:"button is-info" %>
    </div>
  </div>
<% end %>

app/views/discussions/_sidebar.html.erb
<!-- Bulma being used below -->

<div class="column is-4 is-offset-1">
  <!-- Area to display most recently signed up members -->
  <h3 class="title is-5 has-text-grey-light">Recent Members</h3>
    <table>
      <tr>
        <% Array(User.all.order('last_seen_at desc')[0..3]).each do |d| %>
          <td>
            <%= link_to gravatar_image_tag(d.email, class:'border-radius-50', size: 5), d %>
          </td>
        <% end %>
      </tr>
      <tr>
        <% Array(User.all.order('last_seen_at desc')[0..3]).each do |d| %>
          <td class="has-text-centered">
            <%= link_to d.username, d %>
          </td>
        <% end %>
      </tr>

      <tr>
        <% Array(User.all.order('last_seen_at desc')[4..7]).each do |d| %>
          <td>
            <%= link_to gravatar_image_tag(d.email, class:'border-radius-50', size: 5), d %>
          </td>
        <% end %>
      </tr>
      <tr>
        <% Array(User.all.order('last_seen_at desc')[4..7]).each do |d| %>
          <td class="has-text-centered">
            <%= link_to d.username, d %>
          </td>
        <% end %>
      </tr>

      <tr>
        <% Array(User.all.order('last_seen_at desc')[8..11]).each do |d| %>
          <td>
            <%= link_to gravatar_image_tag(d.email, class:'border-radius-50', size: 5), d %>
          </td>
        <% end %>
      </tr>
      <tr>
        <% Array(User.all.order('last_seen_at desc')[8..11]).each do |d| %>
          <td class="has-text-centered">
            <%= link_to d.username, d %>
          </td>
        <% end %>
      </tr>
    </table>

  <br/>
  <br/>

  <!-- Show discussion topics and allow users to select topics they would like to see -->
  <%= link_to 'Topics', topics_path, class: 'title is-5 has-text-grey-light' %>
  <br>
  <br>

  <form class="filter_form" method="get">
    <div class="buttons">
      <% @topics.where.not(topic: "News").each do |t| %>
        <label class="button is-info is-rounded is-outlined">
          <%= check_box_tag("toggle[]", t.id)%>
          <%= t.topic %>
        </label>
      <% end %>
    </div>
    <button type="submit" class='button is-info'>Selected Post</button>
    <%= link_to 'New Topic', new_topic_path, class: 'button is-info' %>
  </form>

  <br/>
  <br/>

  <!-- Top posts on the forum based off view count -->
  <h3 class="title is-5 has-text-grey-light">Top Posts</h3>
  <table class="table is-fullwidth is-striped">
    <tbody>
      <% Discussion.all.sort_by{|d| d[:view_count]}.reverse[0..4].each do |d| %>
      <tr>
        <td> <%= link_to d.title, d %> </td>
        <td style="width:15%"> <%= d.view_count %> <i class="far fa-eye"></i></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

  <!-- Static links to other webpages -->
  <h3 class="title is-5 has-text-grey-light">Links</h3>
  <div class="buttons">
    <%= link_to "Google", "http://www.google.com", class: 'button is-rounded is-outlined' %>
    <%= link_to "RMIT", "https://www.rmit.edu.au/", class: 'button is-rounded is-outlined' %>
    <%= link_to "Ruby on Rails", "https://rubyonrails.org/", class: 'button is-rounded is-outlined' %>
  </div>
</div>

app/views/discussions/edit.html.erb
<h1 class = "title is-3">Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<div class = "columns">

  <%# Load the discussions page in shared %>
  <%= render 'shared/discussions' %>
  <%= render 'sidebar' %>

</div>

app/views/discussions/new.html.erb
<h1 class = "title is-size-3">New Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<%# Bulma used below %>

<div class="columns">
  <div class="column is-8">
    <h1 class="title is-2 has-text-grey discussion-title"><%= @discussion.title %></h1>
    <h3 class="subtitle is-5 has-text-grey-lighter">by <%= @discussion.user.username %> in <%= link_to @discussion.topic.topic, @discussion.topic %></h3>
    <div class="level">
      <div class="level-left"></div>
      <div class="level-right">
      	<%# Check if the user is the author of a discussion, if so, show edit/delete options %>
        <%# Check is in discussions_helper.rb %>
        <% if discussion_author(@discussion) %>
        <div class="buttons">
            <%= link_to 'Edit', edit_discussion_path(@discussion), class:'button'%>
            <%= link_to 'Delete', discussion_path(@discussion), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class:'button' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="content"><%= markdown(@discussion.content) %></div>

    <h2 class="subtitle is-5 has-text-grey"><%= @discussion.replies.count %> Replies</h2>

    <div id="discussion-replies">
      <%# This looks for a partial called reply
      <%# Render the replies and load _reply.html.erb %>
      <%= render @discussion.replies %>
    </div>

    <hr />

    <h3 class="subtitle is-3 has-text-grey">Leave a reply</h3>
    <%# Check if the user is signed in %>
    <% if user_signed_in? %>
      <%# If the user is signed in, load replies/form %>
      <%= render 'replies/form' %>
    <% else %>
    <%# If the user isn't signed in, display %>
    <p>To reply, please <%= link_to 'login', login_path %>. If you don't have an account with us, please 
      <%= link_to 'Sign up', signup_path %> for one today.</p>
    <% end %>

  </div>

  <%= render 'sidebar' %>

</div>