config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    resources :discussions, only: [:index]
    resources :replies, only: [:index]
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :custom_user_posts
  get 'users/:id/user_replies' => 'users#user_replies', :as => :custom_user_replies

  resources :topics
  resources :discussions do
  	resources :replies
  end
  resources :discussions do
    member do
      get :users
    end
  end

  root 'discussions#index'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/topic.rb
class Topic < ApplicationRecord

	# Creating relationships for the model
	has_many :discussions
	# Essentially creating a join table between the two tables
	has_many :users, through: :discussions

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    # Get all the discussions and order them via created date
    @discussions = Discussion.all.order('created_at desc')
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    # Get the discussions that match the selected topic id
    @discussions = Discussion.where('topic_id = ?', @topic_id)
    # Get all the topics, no selected sort by here
    @topics = Topic.all
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:topic)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  	<%= f.error_notification %>

 	<div class="field">
   		<div class="control">
    		<%= f.input :topic, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
   		</div>
 	</div>

 	<%= f.button :submit, class: 'button is-info' %>
<% end %>

app/views/topics/edit.html.erb
<h1 class="title is-3">Editing Topics</h1>

<%= render 'form', topic: @topic %>

app/views/topics/index.html.erb
<h1 class="title is-2">Topics</h1>

<%# if has_role?(:admin) %>
<div class="level">
  <div class="level-left"></div>
  <div class="level-right">
    <%= link_to 'New Topic', new_topic_path, class:'button is-dark' %>
  </div>
</div>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
    <tr>
      <td><%= link_to topic.topic, topic %></td>
      <td>
        <div class="buttons is-right">
          <%= link_to 'View Topic', topic, class:'button' %>
          <%= link_to 'Edit', edit_topic_path(topic), class:'button' %>
          <%= link_to 'Delete', topic, class:'button is-danger', method: :delete, data: { confirm: "Are you sure you want to delete this topic? " } %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>

<%# else %>
 <%# <p class="has-text-center">Sorry! You don't have access this page.</p> %>
<%# end %>

app/views/topics/new.html.erb
<div class="columns is-centered">
  	<div class="column is-4">
    	<h1 class="title is-3">Create a new topic</h1>
    	<%= render 'form', topic: @topic %>
  	</div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @topic.topic %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>