config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    resources :discussions, only: [:index]
    resources :replies, only: [:index]
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :custom_user_posts
  get 'users/:id/user_replies' => 'users#user_replies', :as => :custom_user_replies

  resources :topics
  resources :discussions do
  	resources :replies
  end
  resources :discussions do
    member do
      get :users
    end
  end

  root 'discussions#index'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :discussions
  has_many :replies, through: :discussions

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  VALID_PASSWORD_REGEX = /\A[a-zA-Z0-9 ]+\z/
  validates :password, presence: true, length: { minimum: 8, maximum: 20 }, format: {with: VALID_PASSWORD_REGEX}, allow_nil: true
  validates :mobile_number, presence: true, length: {minimum: 10, maximum: 13}, numericality: {only_integer: true}
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit,:update]
  before_action :correct_user, only: [:edit,:update]


  def index
    @users = User.all
    @discussions = @user.discussions
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      @user.update_attribute(:date_created, Date.today)
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def user_posts
    @user = User.find(params[:id])
    @discussions = @user.discussions
  end

  def user_replies
    @user = User.find(params[:id])
    @replies = Reply.all.where(:user_id => @user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def user_params
    params.require(:user).permit(:username, :date_created, :city, :email, :mobile_number, :password,
                                 :password_confirmation)
  end


  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end


  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end


end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :mobile_number %>
  <%= f.text_field :mobile_number, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <p>Already a member? <%= link_to "Login now", login_path %></p>
<% end %>

app/views/users/_profile.html.erb
<div>
  <div class="container">
    <div class="d-flex justify-content-center h-100">
      <center>
        <%= gravatar_for @user %>
        <br>
        <br>
        <h3 style="font-family: bold, 'Arial Black'"> <%= @user.username %></h3>

        <br>

        <!--  get user city, display N/A if nil-->
        <%if @user.city != nil %>
          <p>City: <%= @user.city %></p>
        <%else %>
          <p>City: N/A</p>
        <%end %>
        <!--  date created-->
        <p>Date Created: <%= @user.created_at.try(:strftime, ('%d-%m-%Y')) %></p>
      </center>
    </div>
  </div>

  <br>
  <div class="row">
    <div class="column">

      <!--  show discussions - start of user discussions loop-->
      <p style="font-family: bold,'Arial Black'">Recent Posts</p>
      <% @user.discussions.order('created_at desc').each do |user_discuss| %>
        <%= link_to user_discuss do %>
          <h3 class="title is-5" id="user_discuss"><%= user_discuss.title %></h3>
        <% end %>
        <p><%= truncate(strip_markdown(user_discuss.content), length: 140) %></p>
        <p><em><small>Posted <%= time_ago_in_words(user_discuss.created_at) %> ago in
          <% if user_discuss.topic %>
            <!-- Link to this topics discussions -->
            <%= link_to user_discuss.topic.topic, user_discuss.topic %>
          <% end %>
        </small>
        </em>
        <hr class="solid">
        </p>
      <%end %>
    </div>

    <div class="column">


     <%= render 'replies' %>
      <!--    end discussion loop-->

    </div>
  </div>


</div>

app/views/users/_replies.html.erb
<!--    show user comments-->
<p style="font-family: bold,'Arial Black'">Recent Comments</p>
<!--    loops through global discussions-->
<%Discussion.all.order('created_at desc').each do |all_discuss| %>
  <!--      loops through each discussion reply-->
  <% all_discuss.replies.each do |c|%>
    <!--        if reply username same as current user show reply-->
    <%if c.user.username == @user.username %>
      <p>Recent Comment: "<%= link_to c.reply, all_discuss %>"</p>
      <p>Time Posted: <%= c.created_at %></p>
      <p>On Discussion: <%= link_to all_discuss.title, all_discuss %></p>
      <hr class="solid">
    <%end %>
  <%end %>
<%end %>

app/views/users/_sidebar.html.erb
<!-- Bulma being used below -->
<%if @user == current_user %>
<div class="column is-2">
    <aside class="menu">
    <p class="menu-label">
        My Account
    </p>
    <ul class="menu-list">
        <li>
            <%= link_to 'My Profile', user_path(current_user), class:"navbar-item" %>
        </li>
        <li>
            <%= link_to 'My Posts', custom_user_posts_path(current_user), class:"navbar-item" %>
        </li>
        <li>
            <%= link_to 'My Comments', custom_user_replies_path(current_user), class:"navbar-item" %>
        </li>
        <li>
            <%= link_to 'Comments to Me', root_path, class:"navbar-item" %>
        </li>
        <li>
          <%= link_to "Settings", edit_user_path(current_user) %>
        </li>
    </ul>
    </aside>
  <%end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<%= render 'sidebar' %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <br>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign Up</h1>
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :mobile_number %>
      <%= f.text_field :mobile_number, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <p>Already a member? <%= link_to "Login now", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class = "columns">
  <%= render 'sidebar' %>
  <%= render 'profile' %>
</div>

app/views/users/user_posts.html.erb
<%= render 'sidebar' %>
<p style="font-family: bold,'Arial Black'">Recent Posts</p>
<% @user.discussions.order('created_at desc').each do |user_discuss| %>
  <%= link_to user_discuss do %>
    <h3 class="title is-5" id="user_discuss"><%= user_discuss.title %></h3>
  <% end %>
  <p><%= truncate(strip_markdown(user_discuss.content), length: 140) %></p>
  <p><em><small>Posted <%= time_ago_in_words(user_discuss.created_at) %> ago in
    <% if user_discuss.topic %>
      <!-- Link to this topics discussions -->
      <%= link_to user_discuss.topic.topic, user_discuss.topic %>
    <% end %>
  </small>
  </em>
  <hr class="solid">
  </p>
<%end %>

app/views/users/user_replies.html.erb
<%= render 'sidebar' %>
<!--    show user comments-->
<p style="font-family: bold,'Arial Black'">Recent Comments</p>
<!--    loops through global discussions-->
<%Discussion.all.order('created_at desc').each do |all_discuss| %>
  <!--      loops through each discussion reply-->
  <% all_discuss.replies.each do |c|%>
    <!--        if reply username same as current user show reply-->
    <%if c.user.username == @user.username %>
      <p>Recent Comment: "<%= link_to c.reply, all_discuss %>"</p>
      <p>Time Posted: <%= c.created_at %></p>
      <p>On Discussion: <%= link_to all_discuss.title, all_discuss %></p>
      <hr class="solid">
    <%end %>
  <%end %>
<%end %>