config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    resources :discussions, only: [:index]
    resources :replies, only: [:index]
  end
  get 'users/:id/user_posts' => 'users#user_posts', :as => :custom_user_posts
  get 'users/:id/user_replies' => 'users#user_replies', :as => :custom_user_replies

  resources :topics
  resources :discussions do
  	resources :replies
  end
  resources :discussions do
    member do
      get :users
    end
  end

  root 'discussions#index'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News+</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Used for reloading the replies without having to refresh the webpage -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Used for icons such as views and replies in the forum -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.min.css">

    <!-- JavaScript for toggleable button -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" 
    integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

  </head>

  <%# The class references below are for the bulma library %>
  <body class="main">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Discussions</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <% if user_signed_in? %>
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to gravatar_image_tag(current_user.email, class:'profilepic', size: 20, alt: current_user.username), current_user, class: "navbar-link" %>
            <div class="navbar-dropdown is-right">
              <%= link_to 'Account', current_user, class:"navbar-item" %>
              <%= link_to "Log Out", logout_path, method: :delete, class:"navbar-item" %>
            </div>
          </div>
         <% else %>
         <div class="navbar-item">
          <div class="field is-grouped">

            <p class="control">
              <%= link_to 'New Discussion', new_discussion_path, class:"button is-info" %>
            </p>

            <p class="control">
              <%= link_to "Sign In", login_path, class: "button is-light"%>
            </p>

            <p class="control">
              <%= link_to "Sign up", signup_path, class: "button is-light" %>
            </p>
          </div>
          </div>
          <% end %>

        </div>
    </div>
  </nav>

  <section class="section">
    <div class="container">
      <%= yield %>
    </div>
  </section>

  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>News+</strong> created by Casey Coulter (s3668759) and Jack Ryan (s3655960), Semester 1 2020.
      </p>
      <p>
        Tutorial: Friday 4:30 PM, Tutor: <strong>Anto Dominic</strong>
      </p>
    </div>
  </footer>

  </body>
</html>